### PR TITLE
Use node 14-slim to fix build

### PR DESCRIPTION
**Pull request by scottolsen**
The verificator status comment is failing, this should fix it.

https://github.com/MerchantsBonding/hubble/runs/1297642600?check_suite_focus=true#step:2:47

### CODE REVIEW

**Comment by ghost** [comment]
So this is effectively locking npm to an older version?

**Review by ghost — APPROVED** [review]

**Comment by scottolsen** [comment]
No, the slim version just excludes some libraries which **_I think_** are causing the problems and we don't need.

> Both the full Node.js image and the ‘-slim’ image are built from Debian Linux (v8 “jessie” at the time of writing this). The major difference being the tools and libraries that are installed by default.
> 
> If you travel the hierarchy of Dockerfile builds and tags, you’ll find that the full version of the image builds from the same core ‘jessie:curl’ tag as the slim version.
> 
> The full version, however, adds a significant number of tools, including:
> 
> source controls software, such as git, subversion, bazaar, and mercurial
> runtime libraries and build tools like make, gcc, g++, and others 
> libraries and API sets such as imagemagick, a dozen other lib* libraries), and others

**Comment by ghost** [comment]
So `slim` includes more stuff than `14-slim` ?

**Comment by scottolsen** [comment]
haha good call! Thought I added the slim, but in fact I didn't.

> So this is effectively locking npm to an older version?

I'll now say yes to this :)

**Pull request merged**
